apiVersion: v1
kind: ServiceAccount
metadata:
  name: updater-cron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: updater-cron
rules:
  - apiGroups:
      - apps
      - ""
    resources:
      - pods
      - deployments
    verbs:
      - list
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: updater-cron-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: updater-cron
subjects:
- kind: ServiceAccount
  name: updater-cron
  namespace: {{ .Release.Namespace }}
