{{- if .Values.andi.liveView.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: andi-lv-salt
type:
  Opaque
data:
  {{ if .Values.global.liveView.value }}
  salt: {{ .Values.global.liveView.value }}
  {{- else }}
  salt: {{ quote .Values.andi.liveView.value }}
  {{ end - }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.targetRelease }}-andi-auth0-client-secret
type: Opaque
stringData:
  {{ if .Values.global.auth.auth0_client_id }}
  auth0_client_id: {{ quote .Values.global.auth.auth0_client_id }}
  {{- else }}
  auth0_client_id: {{ quote .Values.andi.auth.auth0_client_id }}
  {{ end -}}
  {{ if .Values.global.auth.auth0_client_secret }}
  auth0_client_secret: {{ quote .Values.global.auth.auth0_client_secret }}
  {{- else }}
  auth0_client_secret: {{ quote .Values.andi.auth.auth0_client_secret }}
  {{ end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.targetRelease }}-andi-postgres-secret
type: Opaque
stringData:
  {{ if .Values.global.postgres.user }}
  user: {{ quote .Values.global.postgres.user }}
  {{- else }}
  user: {{ quote .Values.andi.postgres.user  }}
  {{ end -}}
  {{ if .Values.global.postgres.password }}
  password: {{ quote .Values.global.postgres.password }}
  {{- else }}
  password: {{ quote .Values.andi.postgres.password }}
  {{ end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.targetRelease }}-andi-aws-credentials
type: Opaque
stringData:
  {{ if .Values.global.objectStore.accessSecret }}
  aws_access_key_secret: {{ quote .Values.global.objectStore.accessSecret }}
  {{- else }}
  aws_access_key_secret: {{ quote .Values.andi.aws.accessKeySecret }}
  {{ end -}}
  {{ if .Values.global.objectStore.accessKey }}
  aws_access_key_id: {{ quote .Values.global.objectStore.accessKey }}
  {{- else }}
  aws_access_key_id: {{ quote .Values.andi.aws.accessKey }}
  {{ end -}}
