apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.targetRelease }}-discovery-streams-redis-secret
type: Opaque
stringData:
  {{ if .Values.global.redis.password }}
  password: {{ quote .Values.global.redis.password }}
  {{- else }}
  password: {{ quote .Values.discoveryStreams.redis.password }}
  {{ end -}}
