{{- if .Values.estuary.liveView.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: estuary-lv-salt
type:
  Opaque
data:
  {{ if .Values.global.liveView.value }}
  salt: {{ .Values.global.liveView.value }}
  {{- else }}
  salt: {{ quote .Values.estuary.liveView.value }}
  {{ end - }}
{{- end }}
