apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.targetRelease }}-forklift-redis-secret
type: Opaque
stringData:
  {{ if .Values.global.redis.password }}
  password: {{ quote .Values.global.redis.password }}
  {{- else }}
  password: {{ quote .Values.forklift.redis.password }}
  {{ end -}}
---
{{ if .Values.forklift.objectStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.targetRelease }}-forklift-aws-credentials
type: Opaque
stringData:
  {{ if .Values.global.objectStore.accessSecret }}
  aws_access_key_secret: {{ quote .Values.global.objectStore.accessSecret }}
  {{- else }}
  aws_access_key_secret: {{ quote .Values.forklift.objectStore.accessKeySecret }}
  {{ end -}}
  {{ if .Values.global.objectStore.accessKey }}
  aws_access_key_id: {{ quote .Values.global.objectStore.accessKey }}
  {{- else }}
  aws_access_key_id: {{ quote .Values.forklift.objectStore.accessKeyId }}
  {{ end -}}
{{ end -}}