apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.targetRelease }}-raptor-auth0-client-secret
type: Opaque
stringData:
  {{ if .Values.global.auth.auth0_client_id }}
  auth0_client_id: {{ quote .Values.global.auth.auth0_client_id }}
  {{- else }}
  auth0_client_id: {{ quote .Values.raptor.auth.auth0_client_id }}
  {{ end -}}
  {{ if .Values.global.auth.auth0_client_secret }}
  auth0_client_secret: {{ quote .Values.global.auth.auth0_client_secret }}
  {{- else }}
  auth0_client_secret: {{ quote .Values.raptor.auth.auth0_client_secret }}
  {{ end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.targetRelease }}-raptor-redis-secret
type: Opaque
stringData:
  {{ if .Values.global.redis.password }}
  password: {{ quote .Values.global.redis.password }}
  {{- else }}
  password: {{ quote .Values.raptor.redis.password }}
  {{ end -}}



