apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      serviceAccountName: hive-metastore
      containers:
      - name: hive-metastore
        image: quay.io/cloudservices/ubi-hive:3.1.2-metastore-008
        ports:
        - containerPort: 8000
        env:
        - name: HOSTNAME
          value: hive-metastore
        - name: HIVE_LOGLEVEL
          value: DEBUG
          {{- with .Values.global.objectStore }}
        - name: S3_HOST
          value: {{ .host }}
        - name: S3_PORT
          value: {{ quote .port }}
        - name: S3_BUCKET_PATH
          value: {{ .hiveStoragePath }}
          {{- end }}
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-persistence-object-store-secret
              key: access_key_id
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-persistence-object-store-secret
              key: access_key_secret
        - name: S3_BUCKET_NAME
          value: {{ .Values.global.buckets.hiveStorageBucket }}
          {{- with .Values.metastore.postgres }}
        - name: POSTGRES_SQL_SERVICE_HOST
          value: {{ .host }}
        - name: POSTGRES_SQL_SERVICE_PORT
          value: {{ quote .port }}
        - name: DATABASE_NAME
          value: {{ .name }}
          {{- end }}
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-persistence-redis-secret
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-persistence-redis-secret
              key: password
        resources:
{{ toYaml .Values.metastore.resources | indent 10 }}