global:
  objectStore:
    accessKey: [ ]
    accessSecret: [ ]

config:
  cron: "*/10 * * * *"
  image: "smartcitiesdata/sauron:0.0.4"
  managedReleaseName: "urban-os"

remoteDeployment:
  gitHttpsCloneUrl: "https://github.com/<Org>/<Repo>.git"
  targetBranch: "main"
  valuesFileFromRepoRoot: "./dev/values.yaml"
  proxyAccountPAT: ""
  secrets:
    andi:
      postgres:
        password: ""
      auth:
        auth0_client_secret: ""

    persistence:
      metastore:
        postgres:
          password: ""

      trino:
        enabled: true

    raptor:
      auth:
        auth0_client_secret: ""

    discovery-api:
      secrets:
        discoveryApiPresignKey: ""
        guardianSecretKey: ""
      postgres:
        password: ""
