config:
  cron: "*/10 * * * *"
  image: "smartcitiesdata/sauron:0.0.2"

serviceAccount:
  # Create a ServiceAccount or use default ServiceAccount if set as false
  create: true
  name: updater-cron

deployments:
  alchemist:
    enabled: true
    major: 0
    minor: 2

  andi:
    enabled: true
    major: 2
    minor: 4

  discovery_api:
    enabled: true
    major: 1
    minor: 3

  discovery_streams:
    enabled: true
    major: 3
    minor: 0

  #TODO: Add support for discovery-ui (Different repo than smartcitiesdata)

  forklift:
    enabled: true
    major: 0
    minor: 19

  raptor:
    enabled: true
    major: 1
    minor: 2

  reaper:
    enabled: true
    major: 2
    minor: 0

  valkyrie:
    enabled: true
    major: 1
    minor: 7
