config:
  cron: "*/10 * * * *"
  image: "smartcitiesdata/sauron:0.0.4"

remoteDeployment:
  gitHttpsCloneUrl: "https://github.com/<Org>/<Repo>.git"
  targetBranch: "main"
  currentDeploymentSha: ""
  valuesFileFromRepoRoot: "./dev/values.yaml"
  proxyAccountPAT: ""
  secrets:
    andi:
      postgres:
        password: ""
      auth:
        auth0_client_secret: ""

    persistence:
      metastore:
        postgres:
          password: ""

      trino:
        enabled: true

    raptor:
      auth:
        auth0_client_secret: ""

    discovery-api:
      secrets:
        discoveryApiPresignKey: ""
        guardianSecretKey: ""
      postgres:
        password: ""

serviceAccount:
  create: true
  name: updater-cron

deployments:
  alchemist:
    enabled: true
    major: 0
    minor: 2

  andi:
    enabled: true
    major: 2
    minor: 3

  discovery_api:
    enabled: true
    major: 1
    minor: 3

  discovery_streams:
    enabled: true
    major: 3
    minor: 0

  #TODO: Add support for discovery-ui (Different repo than smartcitiesdata)

  forklift:
    enabled: true
    major: 0
    minor: 19

  raptor:
    enabled: true
    major: 1
    minor: 2

  reaper:
    enabled: true
    major: 2
    minor: 1

  valkyrie:
    enabled: true
    major: 1
    minor: 7
