apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cron
spec:
  schedule: "{{ .Values.config.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: {{ .Values.serviceAccount.name }}
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.config.image }}
              imagePullPolicy: Always
              env:
                - name: GIT_HTTPS_CLONE_URL
                  value: {{ .Values.remoteDeployment.gitHttpsCloneUrl }}
                - name: TARGET_BRANCH
                  value: {{ .Values.remoteDeployment.targetBranch }}
                - name: CURRENT_DEPLOYMENT_SHA
                  value: {{ .Values.remoteDeployment.currentDeploymentSha }}
              {{ if .Values.remoteDeployment.enabled }}
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-sauron-github-pat
                      key: token
              {{ end -}}
              command:
                - "/bin/bash"
                - "-c"
                - "/usr/local/bin/image_patch_update_script.sh"
                - "/usr/local/bin/deployment_update_script.sh"
              volumeMounts:
                - mountPath: /usr/local/bin/image_patch_update_script.sh
                  name: sauron-commands
                  subPath: image_patch_update_script.sh
                - mountPath: /usr/local/bin/deployment_update_script.sh
                  name: sauron-commands
                  subPath: deployment_update_script.sh
          volumes:
          - name: sauron-commands
            configMap:
              name: sauron-commands
              defaultMode: 0777
          restartPolicy: Never