{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: "{{ .Values.kafka.strimziCluster }}"
spec:
  kafka:
    replicas: {{ .Values.kafka.defaultReplicas }}
    listeners:
      plain: {}
      tls: {}
    config:
      num.partitions: 30
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      auto.create.topics.enable: false
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storageSize }}
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
      failureThreshold: 20
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    resources:
{{ toYaml .Values.kafka.resources | indent 6 }}
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
  zookeeper:
    replicas: {{ .Values.kafka.defaultReplicas }}
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
{{- end }}
