global:
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  redis:
    host: redis.external-services
    password: ""
  ingress:
    dnsZone: ""
    rootDnsZone: ""

dashboard:
  title: "Dashboard Metrics"

image:
  repository: smartcitiesdata/discovery_streams
  tag: development
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 512Mi
    cpu: "1"
    
monitoring:
  targetPort: 9002

service:
  type: NodePort
  port: 80
  targetPort: 4000

ingress:
  annotations: