apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: pipeline
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.defaultReplicas }}
    listeners:
      plain: {}
      tls: {}
    config:
      num.partitions: 30
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      auto.create.topics.enable: false
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storageSize }}
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 45
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 45
    resources:
{{ toYaml .Values.kafka.resources | indent 6 }}
    rack:
      topologyKey: failure-domain.beta.kubernetes.io/zone
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
    tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    affinity:
{{ toYaml .Values.affinity | indent 6 }}
  zookeeper:
    replicas: {{ .Values.kafka.defaultReplicas }}
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 45
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 45
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
    tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    affinity:
{{ toYaml .Values.affinity | indent 6 }}
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: "100m"
          memory: 512Mi
        limits:
          cpu: "500m"
          memory: 512Mi
    tlsSidecar:
{{ toYaml .Values.tlsSidecar | indent 6 }}
