apiVersion: v1
appVersion: "1.0"
description: A custom chart for the vault secrets engine in support of the UrbanOS platform.
name: vault
version: 1.3.5
sources:
  - https://github.com/hashicorp/vault
