apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: KAFKA_BROKERS
          value: {{ .Values.global.kafka.brokers | default (include "kafka.brokerservice" .) }}
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: REDIS_SSL
          value: {{ quote .Values.global.redis.sslEnabled }}
{{- if .Values.global.redis.port }}
        - name: REDIS_PORT
          value: {{ quote .Values.global.redis.port }}
{{- end }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-discovery-streams-redis-secret
              key: password
        - name: RUN_IN_KUBERNETES
          value: "true"
        - name: RAPTOR_URL
          value: {{ quote .Values.global.auth.raptor_url }}
        - name: METRICS_PORT
          value: {{ quote .Values.monitoring.targetPort }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
