apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  server_config.json: |
    {{ .Values.vault.config | toJson }}

  admin_policy.hcl: |
    path "*" {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }
  {{ range .Values.vault.policies }}
  {{ .name }}_policy.hcl: |
    path "{{ .path }}" {
      capabilities = ["read", "list"]
    }
  {{ end -}}
