apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.vault.storageClassName }}
  storageClassName: {{ .Values.vault.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.vault.volumeSize }}
