apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      serviceAccountName: discovery-api
      containers:
      - name: discovery-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: KAFKA_BROKERS
            value: {{ .Values.global.kafka.brokers }}
          - name: REDIS_HOST
            value: {{ .Values.global.redis.host }}
          - name: REDIS_PORT
            value: {{ quote .Values.global.redis.port }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-redis-secret
                key: password
          - name: REDIS_SSL
            value: {{ quote .Values.global.redis.sslEnabled }}
          - name: PRESTO_URL
            value: {{ .Values.global.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
          - name: HOST
{{- if .Release.Namespace }}
            value: data.{{ .Release.Namespace }}.{{ .Values.global.ingress.rootDnsZone }}
{{- else }}
            value: data.{{ .Values.global.ingress.rootDnsZone }}
{{- end }}
          - name: ALLOWED_ORIGINS
            value: {{ .Values.global.ingress.rootDnsZone }},{{ .Values.global.ingress.dnsZone }}
          - name: PRESIGN_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-presign-key
                key: discovery-api-presign-key
          - name: GUARDIAN_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-guardian-secret-key
                key: guardian-secret-key
          - name: HOSTED_FILE_BUCKET
            value: {{ .Values.global.buckets.hostedFileBucket }}
          - name: HOSTED_FILE_REGION
            value: {{ .Values.global.buckets.region }}
          - name: POSTGRES_HOST
            value: {{ .Values.postgres.host }}
          - name: POSTGRES_DBNAME
            value: {{ .Values.postgres.dbname }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-postgres-secret
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: {{ quote .Values.postgres.port }}
          - name: POSTGRES_VERIFY_SNI
            value: {{ quote .Values.postgres.verifySNI }}
          - name: AUTH_JWT_ISSUER
            value: {{ quote .Values.global.auth.jwt_issuer }}
          - name: AUTH_JWKS_ENDPOINT
            value: {{ quote .Values.auth.jwks_endpoint }}
          - name: AUTH_USER_INFO_ENDPOINT
            value: {{ quote .Values.auth.user_info_endpoint }}
          - name: AUTH_DOMAIN
            value: {{ quote .Values.global.auth.auth0_domain }}
          - name: AUTH_CLIENT_ID
            value: {{ quote .Values.auth.client_id }}
          - name: AUTH_REDIRECT_BASE_URL
            value: {{ quote .Values.auth.redirect_base_url }}
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.elasticsearch.host }}
          - name: ELASTICSEARCH_TLS_ENABLED
            value: {{ quote .Values.elasticsearch.tls }}
          - name: METRICS_PORT
            value: {{ quote .Values.monitoring.targetPort }}
          - name: RAPTOR_URL
            value: {{ quote .Values.global.auth.raptor_url }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-aws-credentials
                key: aws_access_key_id
          - name: AWS_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-aws-credentials
                key: aws_access_key_secret
          {{ if .Values.aws.s3HostName }}
          - name: S3_HOST_NAME
            value: {{ .Values.aws.s3HostName }}
          - name: S3_PORT
            value: {{ quote .Values.aws.s3Port }}
          {{ end -}}
