global:
  buckets:
    region: us-west-2
    hostedFileBucket: "example-file-bucket"
    hiveStorageBucket: "example-hive-bucket"
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  presto:
    url: http://platform-kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services
    password: ""
  vault:
    endpoint: vault.vault:8200

replicaCount: 1
image:
  repository: smartcitiesdata/odo
  tag: development
  pullPolicy: Always

resources:
  limits:
    memory: 2Gi
    cpu: 300m
  requests:
    memory: 2Gi
    cpu: 300m

monitoring:
  targetPort: 9002

service:
  type: NodePort
  port: 80
  targetPort: 4000

aws:
  accessKeyId: ""
  accessKeySecret: ""
