global:
  auth:
    jwt_issuer: ""
    auth0_domain: ""
  buckets:
    region: us-west-2
    hostedFileBucket: "dataset-bucket"
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  presto:
    url: http://platform-kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services
    password: ""
  vault:
    endpoint: vault.vault:8200
  ingress:
    rootDnsZone: localhost
    dnsZone: localhost

resources:
  limits:
    memory: 512Mi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 1

replicaCount: 1

ingress:
  annotations:

service:
  name: discovery-api
  type: NodePort
  port: 80
  auth_string: ""

image:
  name: smartcitiesdata/discovery_api
  tag: development
  pullPolicy: IfNotPresent

monitoring:
  targetPort: 9002

nodeSelector: {}
tolerations: []
affinity: {}

presto:
  catalog: "hive"
  schema: "default"

ldap:
  host: "ldap.example.com"
  base: "dc=example,dc=com"
  user: "binduser"
  account:
    subdn: "cn=users,cn=accounts"

postgres:
  host: "example.com"
  port: "5432"
  dbname: "postgres"
  user: "postgres"
  password: "password"

elasticsearch:
  host: "es.example.com"

auth:
  domain: "example.com"
  client_id: "1234"
  redirect_base_url: "http://localhost"
  jwks_endpoint: "https://example.com/.well-known/jwks.json"
  jwt_issuer: "https://example.com/"
  user_info_endpoint: "https://example.com/userinfo"

secrets:
  discoveryApiPresignKey: ""

aws:
  accessKeyId: ""
  accessKeySecret: ""
