apiVersion: v2
appVersion: "1.0"
description: "A combination of the community Prometheus and Grafana charts."
name: monitoring
version: 1.1.2

dependencies:
  - name: prometheus
    version: 19.3.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.50.5
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
