# optional annotation overrides
global:
  ingress:
    annotations: {}

# A place to define a healthcheck path or other grafana specific annotations
grafanaIngress:
  annotations: {}

# A place to define a healthcheck path or other prometheus specific
# annotations
prometheusIngress:
  annotations: {}

grafana:
  adminUser: admin
  fullnameOverride: monitoring-grafana
  rbac:
    namespaced: true
  serviceAccount:
    create: false
    name: default
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  service:
    enabled: true
    type: NodePort
  sidecar:
    dashboards:
      enabled: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
        - name: "kube"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kube
        - name: "urbanos"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/urbanos
  dashboards:
    kube:
      kube-prometheus:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      kube-namespace:
        gnetId: 6876
        revision: 2
        datasource: Prometheus
      kube-cluster:
        gnetId: 6873
        revision: 2
        datasource: Prometheus
      kube-pods:
        gnetId: 6879
        revision: 1
        datasource: Prometheus
    urbanos:
      urban-os-pipeline-health:
        gnetId: 14805
        revision: 1
        datasource: Prometheus
      urban-os-overview:
        gnetId: 14806
        revision: 1
        datasource: Prometheus
      urban-os-kube-all-nodes:
        gnetId: 14810
        revision: 1
        datasource: Prometheus
      urban-os-kafka-exporter:
        gnetId: 14809
        revision: 1
        datasource: Prometheus
      urban-os-phoenix-api-metrics:
        gnetId: 14811
        revision: 1
        datasource: Prometheus
    # Additional deployment specific dashboards may be
    # added under the "default" provider:
    # default:
    #   custom-dashboard-name:
    #     gnetId: 14811 (dashboard id from https://grafana.com/grafana/dashboards)
    #     revision: 1
    #     datasource: Prometheus

prometheus:
  serviceAccounts:
    server:
      create: false
      name: default

  server:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 500Mi
        cpu: 250m

  prometheus-pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: false
