apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying kafka via strimzi
name: kafka
version: 1.1.9
sources:
  - https://github.com/strimzi/strimzi-kafka-operator
  - https://github.com/apache/kafka
dependencies:
  - name: strimzi-kafka-operator
    version: 0.23.0
    repository: http://strimzi.io/charts/
