apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying kafka via strimzi
name: kafka
version: 1.0.1

dependencies:
  - name: strimzi-kafka-operator
    version: 0.22.0
    repository: http://strimzi.io/charts/
