kafka:
  version: 2.5.1
  broker: pipeline-kafka-bootstrap:9092
  storageSize: 100Gi
  defaultPartitions: 1
  defaultReplicas: 3
  topics:
    - name: streaming-persisted
    - name: streaming-dead-letters
    - name: event-stream
  resources:
    requests:
      cpu: 1400m
      memory: 12500M
    limits:
      cpu: 1400m
      memory: 12500M

strimzi-kafka-operator:
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 100m

tlsSidecar:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

tolerations:
  - key: scos.run.kafka
    operator: Equal
    value: "true"
    effect: NoExecute

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scos.run.kafka
              operator: In
              values:
                - "true"
