apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "odo.chart" . }}
    app.kubernetes.io/name: {{ include "odo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "odo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "odo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /downloads
          name: download-dir
        env:
        - name: CLOUD_REGION
          value: {{ .Values.global.buckets.region }}
        - name: HOSTED_FILE_BUCKET
          value: {{ .Values.global.buckets.hostedFileBucket }}
        - name: KAFKA_BROKERS
          value: {{ .Values.global.kafka.brokers | default (include "kafka.brokerservice" .) }}
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: SECRETS_ENDPOINT
          value: {{ .Values.global.vault.endpoint }}
        - name: WORKING_DIR
          value: {{ .Values.workingDirectory }}
        - name: METRICS_PORT
          value: {{ quote .Values.monitoring.targetPort }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ quote .Values.aws.accessKeyId }}
        - name: AWS_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-odo-aws-access-key-secret
              key: aws_access_key_secret
      volumes:
      - name: download-dir
        emptyDir: {}
