global:
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  redis:
    host: redis.external-services
    password: ""
  auth:
    auth0_domain: ""

image:
  repository: smartcitiesdata/raptor
  tag: development
  pullPolicy: Always

replicaCount: 1

auth:
  auth0_client_id: ""
  auth0_client_secret: ""

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 512Mi
    cpu: "1"

monitoring:
  targetPort: 9002

service:
  type: NodePort
  port: 80
  targetPort: 80
