global:
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  redis:
    host: redis.external-services
    port: 6379
    sslEnabled: false
  auth:
    auth0_domain: ""

image:
  repository: smartcitiesdata/raptor
  tag: development
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 512Mi
    cpu: "1"

monitoring:
  targetPort: 9002

service:
  type: NodePort
  port: 80
  targetPort: 4000
