#!/bin/bash

which helm-docs

# Redirect output to stderr.
exec 1>&2

is_installed=$(helm-docs --version)
expected_installed_substring="helm-docs version"

if [[ "$is_installed" =~ "$expected_installed_substring" ]] ; then
    echo "Running helm docs"
    helm-docs
    git add 'charts/*/README.md'
else
    echo "Helm docs was not found. is_installed=$is_installed"
    if [ "$OSTYPE" == "darwin"* ]; then
        echo "Installing with homebrew"
        brew install norwoodj/tap/helm-docs
        helm-docs
        git add 'charts/*/README.md'
    else
        echo 'Pre-commit hook did not detect helm-docs is installed. Please follow instructions from https://github.com/norwoodj/helm-docs to install'
	echo "PATH=$PATH"
        exit 1
    fi
fi

