dockerPatchUpdates:
  alchemist:
    enabled: true
    major: 0
    minor: 2

  andi:
    enabled: true
    major: 2
    minor: 2

  discovery_streams:
    enabled: true
    major: 2
    minor: 2

  forklift:
    enabled: true
    major: 0
    minor: 17

  reaper:
    enabled: true
    major: 2
    minor: 0

  valkyrie:
    enabled: true
    major: 1
    minor: 7



    #TODO: Add support for discovery-ui (Different repo than smartcitiesdata)




