apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.prometheusIngress.annotations }}
{{ toYaml .Values.prometheusIngress.annotations | trim | indent 4 }}
{{- end }}
{{- if .Values.global.ingress.annotations }}
{{ toYaml .Values.global.ingress.annotations | trim | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: monitoring-prometheus-server
    servicePort: 80
  rules:
  - host: prometheus.{{ .Values.global.ingress.dnsZone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
