apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.prometheusIngress.annotations }}
{{ toYaml .Values.prometheusIngress.annotations | trim | indent 4 }}
{{- end }}
{{- if .Values.global.ingress.annotations }}
{{ toYaml .Values.global.ingress.annotations | trim | indent 4 }}
{{- end }}
spec:
  rules:
  - host: prometheus.{{ .Release.Namespace }}.{{ .Values.global.ingress.dnsZone }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-prometheus-server
            port:
              number: 80
