global:
  auth:
    jwt_issuer: ""
    auth0_domain: ""
  buckets:
    region: "us-west-2"
    hostedFileBucket: ""
  kafka:
    brokers: pipeline-kafka-bootstrap:9092
  presto:
    url: http://kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services
    password: ""
  vault:
    endpoint: vault:8200
  ingress:
    dnsZone: ""
    rootDnsZone: ""
    port: 80
  objectStore:
    accessKey: []
    accessSecret: []

forklift:
  fullnameOverride: forklift
  enabled: true
reaper:
  fullnameOverride: reaper
  enabled: true
valkyrie:
  fullnameOverride: valkyrie
  enabled: true
  replicaCount: 1
odo:
  enabled: true
andi:
  fullnameOverride: andi
  enabled: true
kafka:
  enabled: true
discovery-api:
  elasticsearch:
    # This is the default location of the chart-provided elasticsearch instance
    host: elasticsearch-master:9200
    # Set this to true to require the api to connect to elasticsearch via https.
    # TLS must be configured on the elasticsearch cluster
    tls: false
  enabled: true
discovery-ui:
  enabled: true
discovery-streams:
  enabled: true

# By default monitoring is disabled as it is optional,
# but we recommend it be enabled for production deployments
monitoring:
  enabled: false

kubernetes-data-platform:
  enabled: true
  presto:
    workers: 2
    jvm:
      maxHeapSize: 1536M
    deploy:
      container:
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
    task:
      writerCount: 1
    deployPrometheusExporter: true
    useJmxExporter: true
  metastore:
    allowDropTable: true
    timeout: 360m
  postgres:
    enable: false
    db:
      name: metastore
      user: metastore
    tls:
      enable: true
      mode: verify-full
      rootCertPath: /etc/ssl/certs/ca-certificates.crt
  minio:
    enable: false

# By default, the urbanOS chart stands up its own elasticsearch instance.
# Disable this if you plan to provide your own.
# TLS will be disabled by default, but can be configured using the chart
#   documentation below
# https://github.com/elastic/helm-charts/tree/master/elasticsearch#configuration
elasticsearch:
  enabled: true
  replicas: 2
raptor:
  fullnameOverride: raptor
  enabled: true