apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      serviceAccountName: discovery-api
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: KAFKA_BROKERS
            value: {{ .Values.global.kafka.brokers }}
          - name: REDIS_HOST
            value: {{ .Values.global.redis.host }}
          - name: REDIS_PASSWORD
            value: {{ .Values.global.redis.password }}
          - name: PRESTO_URL
            value: {{ .Values.global.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
          - name: HOST
            value: data.{{ .Values.global.ingress.rootDnsZone }}
          - name: ALLOWED_ORIGINS
            value: {{ .Values.global.ingress.rootDnsZone }},{{ .Values.global.ingress.dnsZone }}
          - name: LDAP_HOST
            value: {{ .Values.ldap.host }}
          - name: LDAP_BASE
            value: {{ .Values.ldap.base }}
          - name: LDAP_USER
            value: {{ .Values.ldap.user }}
          - name: LDAP_ACCOUNT_SUBDN
            value: {{ .Values.ldap.account.subdn }}
          - name: PRESIGN_KEY
            valueFrom:
              secretKeyRef:
                name: discovery-api-presign-key
                key: discovery-api-presign-key
          - name: GUARDIAN_KEY
            valueFrom:
              secretKeyRef:
                name: guardian-secret-key
                key: guardian-secret-key
          - name: HOSTED_FILE_BUCKET
            value: {{ .Values.environment }}-{{ .Values.global.buckets.hostedFileBucket }}
          - name: HOSTED_FILE_REGION
            value: {{ .Values.global.buckets.region }}
          - name: SECRETS_ENDPOINT
            value: {{ .Values.global.vault.endpoint }}
          - name: POSTGRES_HOST
            value: {{ .Values.postgres.host }}
          - name: POSTGRES_DBNAME
            value: {{ .Values.postgres.dbname }}
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: POSTGRES_PORT
            value: {{ quote .Values.postgres.port }}
          - name: AUTH_JWT_ISSUER
            value: {{ quote .Values.global.auth.jwt_issuer }}
          - name: AUTH_JWKS_ENDPOINT
            value: {{ quote .Values.auth.jwks_endpoint }}
          - name: AUTH_USER_INFO_ENDPOINT
            value: {{ quote .Values.auth.user_info_endpoint }}
          - name: AUTH_DOMAIN
            value: {{ quote .Values.global.auth.auth0_domain }}
          - name: AUTH_CLIENT_ID
            value: {{ quote .Values.auth.client_id }}
          - name: AUTH_REDIRECT_BASE_URL
            value: {{ quote .Values.auth.redirect_base_url }}
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.elasticsearch.host }}
          - name: METRICS_PORT
            value: {{ quote .Values.monitoring.targetPort }}
          - name: AWS_ACCESS_KEY_ID
            value: {{ quote .Values.aws.accessKeyId }}
          - name: AWS_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-discovery-api-aws-access-key-secret
                key: aws_access_key_secret
