global:
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  presto:
    url: http://platform-kubernetes-data-platform-presto:8080
  redis:
    host: redis.external-services
    password: ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

replicaCount: 1

image:
  repository: smartcitiesdata/forklift
  tag: development
  pullPolicy: Always

service:
  type: ClusterIP

kafka:
  #comma delimited list of kafka seed brokers
  dataTopicPrefix: "transformed"
  outputTopic: "streaming-persisted"

nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}

kdp:
  user: "forklift"

monitoring:
  targetPort: 9002

profiling_enabled: false

# Set compactionSchedule to a valid cron string such as "00 01 * * *" (This will run compaction nightly at 1:00am)
compactionSchedule: "0 * * * *"
# Special compaction datasets use the variant compaction introduced in https://github.com/Datastillery/smartcitiesdata/pull/950
# This is a comma seperated list of dataset ids, and will only be used if a compactionSchedule is provided. WARNING: tables will be mutated to enable the variant compaction process
specialCompactionDatasets: null
