apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-ui
  template:
    metadata:
      labels:
        app: discovery-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: discovery-ui
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
          - name: "API_HOST"
            value: {{ .Values.env.api_host }}
          - name: "GTM_ID"
            value: {{ .Values.env.gtm_id }}
          - name: "BASE_URL"
            value: {{ .Values.env.base_url }}
          - name: "STREETS_TILE_LAYER_URL"
            value: {{ .Values.env.streets_tile_layer_url }}
          - name: "LOGO_URL"
            value: {{ .Values.env.logo_url | default "null" }}
          - name: "MAPBOX_ACCESS_TOKEN"
            value: {{ .Values.env.mapbox_access_token }}
          - name: "AUTH0_DOMAIN"
            value: {{ .Values.global.auth.auth0_domain }}
          - name: "AUTH0_CLIENT_ID"
            value: {{ .Values.env.auth0_client_id }}
          - name: "AUTH0_AUDIENCE"
            value: {{ .Values.env.auth0_audience }}
          - name: "ADDITIONAL_CSP_HOSTS"
            value: "{{ .Values.env.additional_csp_hosts }}"
          {{ if .Values.env.contribute_host }}
          - name: CONTRIBUTE_HOST
            value: {{.Values.env.contribute_host | quote }}
          {{ end -}}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}