apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-ui
  template:
    metadata:
      labels:
        app: discovery-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: discovery-ui
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /opt/app-root/src/config.js
          name: discovery-ui-configs
          subPath: config.js
        - mountPath: /opt/app-root/etc/nginx.default.d/default.conf
          name: discovery-ui-configs
          subPath: default.conf
      volumes:
      - name: discovery-ui-configs
        configMap:
          name: discovery-ui-configs
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}