global:
  auth:
    auth0_domain: ""
  ingress:
    rootDnsZone: localhost
    dnsZone: localhost

service:
  name: discovery-ui
  type: NodePort
  port: 80

image:
  name: smartcitiesdata/discovery_ui
  tag: development
  environment: "local"
  pullPolicy: Always

env:
  api_host: "https://data.example.com"
  #contribute_host: "https://sharedata.example.com" #Optional location for an associated public Andi deployment
  gtm_id: "GTM-EXAMPLE"
  base_url: "example.com"
  streets_tile_layer_url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  logo_url: null
  footer_left_side_text: "© 2022 UrbanOS. All rights reserved."
  footer_links: "[]"
  mapbox_access_token: ""
  auth0_domain: ""
  auth0_client_id: ""
  auth0_audience: ""
  additional_csp_hosts: ""

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  annotations:
