{{- if .Values.secrets.live_view.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: andi-lv-salt
type:
  Opaque
data:
  salt: {{ .Values.secrets.live_view.value }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-andi-auth0-client-secret
type: Opaque
stringData:
  auth0_client_secret: {{ quote .Values.auth.auth0_client_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-andi-aws-credentials
type: Opaque
stringData:
  aws_access_key_secret: {{ .Values.global.objectStore.accessSecret | default .Values.aws.accessKeySecret | quote }}
  aws_access_key_id: {{ .Values.global.objectStore.accessKey | default .Values.aws.accessKeyId | quote}}