name: 'Version Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: 'Validate Version'
        run: |
          curl -L --output chart_checker https://github.com/espiridion87/chart_checker/releases/download/1.0.0/chart_checker
          chmod +x chart_checker
          curl -o index.yaml https://raw.githubusercontent.com/UrbanOS-Public/charts/gh-pages/index.yaml
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == *Chart.yaml ]] # * is used for pattern matching
            then
              ./chart_checker $changed_file index.yaml
            fi
          done
