apiVersion: v1
kind: Service
metadata:
  name: {{ include "odo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "odo.name" . }}
  annotations:
    prometheus.io/port:  "{{ .Values.monitoring.targetPort }}"
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: {{ include "odo.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
